
//Usuarios

###
GET http://localhost:5000/api/v1/obtener



###
GET http://localhost:5000/api/v1/login/Reyner/123


//Comentarios

###
GET http://localhost:5000/api/v1/comentarios/obtener

###
POST http://localhost:5000/api/v1/comentarios/postear
Content-Type: application/json

{
    "usuario": "Roxana",
    "comentario": "Como estas",
    "fecha": "11-17-2017"
}